// Package streams implements the cloud-side stream URL minting service (KAI-255).
//
// Architectural seam #5: token SIGNING is cloud-side only. Verification happens
// at Recorder/Gateway via the JWKS endpoint served here. Do not embed an
// issuer in any on-prem component.
package streams

import (
	"context"
	"crypto"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"net/http"
	"os"

	"github.com/bluenviron/mediamtx/internal/shared/streamclaims"
)

// SigningKeySource is the seam for loading the cloud signing key. The cloud
// platform signs with RS256; the private key lives in AWS KMS in production
// and in a PEM file or env var in tests and local dev.
//
// Implementations must be safe for concurrent use.
type SigningKeySource interface {
	// LoadPrivateKey returns the signer backed by the cloud RSA private key.
	// Production: AWS KMS-backed signer (KMS never exposes the raw key bytes).
	// Test/dev: file-backed or env-backed concrete *rsa.PrivateKey.
	LoadPrivateKey(ctx context.Context) (crypto.Signer, error)
}

// FileSigningKeySource reads an RSA private key from a PEM file on disk.
// It is the test/dev/local implementation. Do not use in production — use
// KMSSigningKeySource (or its stub) once AWS KMS is wired.
type FileSigningKeySource struct {
	// Path is the filesystem path to the PKCS#8 or PKCS#1 PEM-encoded
	// RSA private key file.
	Path string
}

// LoadPrivateKey reads and parses the PEM key file.
func (f *FileSigningKeySource) LoadPrivateKey(_ context.Context) (crypto.Signer, error) {
	data, err := os.ReadFile(f.Path)
	if err != nil {
		return nil, fmt.Errorf("streams: FileSigningKeySource: read %q: %w", f.Path, err)
	}
	return parseRSAPrivateKeyPEM(data)
}

// EnvSigningKeySource reads an RSA private key from an environment variable
// whose value is a PEM block. Useful in CI environments and Docker Compose.
type EnvSigningKeySource struct {
	// EnvVar is the name of the environment variable holding the PEM key.
	EnvVar string
}

// LoadPrivateKey reads and parses the PEM key from the environment.
func (e *EnvSigningKeySource) LoadPrivateKey(_ context.Context) (crypto.Signer, error) {
	data := os.Getenv(e.EnvVar)
	if data == "" {
		return nil, fmt.Errorf("streams: EnvSigningKeySource: env var %q is empty or unset", e.EnvVar)
	}
	return parseRSAPrivateKeyPEM([]byte(data))
}

// StaticSigningKeySource holds an already-loaded signer. Used in tests to
// inject an ephemeral key generated by streamclaims.GenerateTestKey.
type StaticSigningKeySource struct {
	Key crypto.Signer
}

// LoadPrivateKey returns the static signer directly.
func (s *StaticSigningKeySource) LoadPrivateKey(_ context.Context) (crypto.Signer, error) {
	if s.Key == nil {
		return nil, fmt.Errorf("streams: StaticSigningKeySource: Key is nil")
	}
	return s.Key, nil
}

// TODO(KAI-production): KMSSigningKeySource — AWS KMS-backed signer via
// github.com/salrashid123/signer or a similar KMS crypto.Signer adapter.
// Key material never leaves KMS; only the signing operation crosses the API.
// The JWKS must be built by calling Issuer.PublicKeySet() with the RSA public
// key obtained via kms.GetPublicKey.

// JWKSHandler returns an http.HandlerFunc that serves the public JWKS for this
// service's issuer at /.well-known/jwks.json.
//
// Recorders and Gateways fetch this endpoint to bootstrap their Verifier. The
// response is the raw JSON returned by streamclaims.Issuer.PublicKeySet().
//
// Cache-Control: max-age=300 matches the token MaxTTL so verifiers that cache
// the JWKS never miss a key for tokens that were valid when minted.
func JWKSHandler(issuer *streamclaims.Issuer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			w.WriteHeader(http.StatusMethodNotAllowed)
			return
		}
		raw, err := issuer.PublicKeySet()
		if err != nil {
			http.Error(w, "failed to build JWKS", http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Cache-Control", "public, max-age=300")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(raw)
	}
}

// parseRSAPrivateKeyPEM attempts to decode a PEM block and parse the key as
// PKCS#1 (RSA PRIVATE KEY) or PKCS#8 (PRIVATE KEY). Returns *rsa.PrivateKey
// wrapped as crypto.Signer.
func parseRSAPrivateKeyPEM(data []byte) (crypto.Signer, error) {
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("streams: no PEM block found in key material")
	}
	switch block.Type {
	case "RSA PRIVATE KEY":
		k, err := x509.ParsePKCS1PrivateKey(block.Bytes)
		if err != nil {
			return nil, fmt.Errorf("streams: parse PKCS1 private key: %w", err)
		}
		return k, nil
	case "PRIVATE KEY":
		raw, err := x509.ParsePKCS8PrivateKey(block.Bytes)
		if err != nil {
			return nil, fmt.Errorf("streams: parse PKCS8 private key: %w", err)
		}
		k, ok := raw.(*rsa.PrivateKey)
		if !ok {
			return nil, fmt.Errorf("streams: PKCS8 key is not RSA (got %T)", raw)
		}
		return k, nil
	default:
		return nil, fmt.Errorf("streams: unsupported PEM block type %q (want RSA PRIVATE KEY or PRIVATE KEY)", block.Type)
	}
}
