#include "NullDecoderBackend.h"

#include <QLoggingCategory>
#include <cstring>

Q_LOGGING_CATEGORY(lcNull, "kaivue.render.null")

namespace Kaivue::Render {

// ---------------------------------------------------------------------------
// Deterministic colour table for up to 64 tiles
// ---------------------------------------------------------------------------
static constexpr uint8_t kTileColours[][3] = {
    {0xFF, 0x40, 0x40}, {0x40, 0xFF, 0x40}, {0x40, 0x40, 0xFF}, {0xFF, 0xFF, 0x40},
    {0xFF, 0x40, 0xFF}, {0x40, 0xFF, 0xFF}, {0xFF, 0xA0, 0x40}, {0xA0, 0xFF, 0x40},
    {0x40, 0xA0, 0xFF}, {0xFF, 0x40, 0xA0}, {0xA0, 0x40, 0xFF}, {0x40, 0xFF, 0xA0},
    {0xE0, 0x60, 0x60}, {0x60, 0xE0, 0x60}, {0x60, 0x60, 0xE0}, {0xE0, 0xE0, 0x60},
    {0xE0, 0x60, 0xE0}, {0x60, 0xE0, 0xE0}, {0xC0, 0x80, 0x40}, {0x80, 0xC0, 0x40},
    {0x40, 0x80, 0xC0}, {0xC0, 0x40, 0x80}, {0x80, 0x40, 0xC0}, {0x40, 0xC0, 0x80},
    {0xFF, 0x60, 0x60}, {0x60, 0xFF, 0x60}, {0x60, 0x60, 0xFF}, {0xFF, 0xFF, 0x60},
    {0xFF, 0x60, 0xFF}, {0x60, 0xFF, 0xFF}, {0xFF, 0xB0, 0x60}, {0xB0, 0xFF, 0x60},
    {0xFF, 0x80, 0x80}, {0x80, 0xFF, 0x80}, {0x80, 0x80, 0xFF}, {0xFF, 0xFF, 0x80},
    {0xFF, 0x80, 0xFF}, {0x80, 0xFF, 0xFF}, {0xFF, 0xC0, 0x80}, {0xC0, 0xFF, 0x80},
    {0xD0, 0x50, 0x50}, {0x50, 0xD0, 0x50}, {0x50, 0x50, 0xD0}, {0xD0, 0xD0, 0x50},
    {0xD0, 0x50, 0xD0}, {0x50, 0xD0, 0xD0}, {0xB0, 0x70, 0x30}, {0x70, 0xB0, 0x30},
    {0xE8, 0x48, 0x48}, {0x48, 0xE8, 0x48}, {0x48, 0x48, 0xE8}, {0xE8, 0xE8, 0x48},
    {0xE8, 0x48, 0xE8}, {0x48, 0xE8, 0xE8}, {0xE8, 0x98, 0x48}, {0x98, 0xE8, 0x48},
    {0xF8, 0x58, 0x58}, {0x58, 0xF8, 0x58}, {0x58, 0x58, 0xF8}, {0xF8, 0xF8, 0x58},
    {0xF8, 0x58, 0xF8}, {0x58, 0xF8, 0xF8}, {0xF8, 0xA8, 0x58}, {0xA8, 0xF8, 0x58},
};
static constexpr uint8_t kGrey[3] = {0x33, 0x33, 0x33};
static constexpr int kNumColours = static_cast<int>(sizeof(kTileColours) / sizeof(kTileColours[0]));

// ---------------------------------------------------------------------------
// NullDecoderBackend
// ---------------------------------------------------------------------------
NullDecoderBackend::NullDecoderBackend() = default;
NullDecoderBackend::~NullDecoderBackend() { shutdown(); }

bool NullDecoderBackend::init(QWindow* /*window*/)
{
    m_initialised = true;
    qCInfo(lcNull) << "NullDecoderBackend initialised (software rasterizer, no GPU)";
    return true;
}

void NullDecoderBackend::resizeSurface(const QSize& size)
{
    m_surfaceSize = size.isValid() ? size : m_surfaceSize;
}

void NullDecoderBackend::beginFrame()
{
    ++m_frameCount;
}

void NullDecoderBackend::drawTile(TileId id, const DecodedFrameRef& frame, const QRectF& dst)
{
    Q_UNUSED(dst);
    if (!frame.isValid()) return;

    // For the null backend the frame was already generated by generateFrame().
    // Nothing to GPU-blit here; the payload is a CPU RGBA buffer.
    Q_UNUSED(id);
}

void NullDecoderBackend::endFrame() {}
void NullDecoderBackend::submitPresent() {}

void NullDecoderBackend::shutdown()
{
    m_buffers.clear();
    m_initialised = false;
}

DecodedFrameRef NullDecoderBackend::generateFrame(TileId id, int width, int height,
                                                   std::int64_t pts)
{
    auto& buf = m_buffers[id.value];
    const std::size_t needed = static_cast<std::size_t>(width * height * 4);
    if (buf.width != width || buf.height != height || buf.rgba.size() != needed) {
        buf.rgba.resize(needed);
        buf.width  = width;
        buf.height = height;
        fillChecker(buf, id);
    }

    DecodedFrameRef ref;
    ref.width   = width;
    ref.height  = height;
    ref.pts     = pts;
    ref.payload = buf.rgba.data();
    return ref;
}

uint32_t NullDecoderBackend::pixelHash(TileId id) const noexcept
{
    auto it = m_buffers.find(id.value);
    if (it == m_buffers.end() || it->second.rgba.empty()) return 0;
    return fnv1a(it->second.rgba.data(), it->second.rgba.size());
}

// static
void NullDecoderBackend::fillChecker(TileBuffer& buf, TileId id) noexcept
{
    const int colIdx = static_cast<int>(id.value % static_cast<uint32_t>(kNumColours));
    const uint8_t* fg = kTileColours[colIdx];

    for (int y = 0; y < buf.height; ++y) {
        for (int x = 0; x < buf.width; ++x) {
            const bool checker = ((x / kCheckerSize) + (y / kCheckerSize)) % 2 == 0;
            const uint8_t* c   = checker ? fg : kGrey;
            uint8_t* px = buf.rgba.data() + (static_cast<std::size_t>(y * buf.width + x) * 4);
            px[0] = c[0]; // R
            px[1] = c[1]; // G
            px[2] = c[2]; // B
            px[3] = 0xFF; // A
        }
    }
}

// static — FNV-1a 32-bit
uint32_t NullDecoderBackend::fnv1a(const uint8_t* data, std::size_t len) noexcept
{
    uint32_t hash = 0x811c9dc5u;
    for (std::size_t i = 0; i < len; ++i) {
        hash ^= static_cast<uint32_t>(data[i]);
        hash *= 0x01000193u;
    }
    return hash;
}

} // namespace Kaivue::Render
