-- KAI-430: recorders table for enrolled Recorder nodes.
--
-- A row is inserted atomically when a Recorder successfully redeems its
-- PairingToken via POST /api/v1/pairing/check-in.
--
-- device_pubkey is the base64url-encoded ed25519 public key submitted by the
-- Recorder during check-in (used for device authentication in later steps).
-- hardware_json stores the full hardware snapshot as opaque JSON.
-- cloud_tenant links the recorder to its cloud-managed tenant (empty for
-- air-gapped sites).

CREATE TABLE IF NOT EXISTS recorders (
    recorder_id   TEXT     NOT NULL PRIMARY KEY,   -- UUID generated by Directory at check-in
    tenant_id     TEXT     NOT NULL DEFAULT '',     -- cloud tenant binding (may be empty)
    device_pubkey TEXT     NOT NULL,               -- base64url ed25519 public key from Recorder
    os_release    TEXT     NOT NULL DEFAULT '',
    hardware_json TEXT     NOT NULL DEFAULT '{}',  -- full hardware snapshot as JSON
    token_id      TEXT     NOT NULL,               -- FK to pairing_tokens.token_id (audit trail)
    enrolled_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at  DATETIME
);

CREATE INDEX IF NOT EXISTS idx_recorders_tenant ON recorders (tenant_id);
CREATE INDEX IF NOT EXISTS idx_recorders_token  ON recorders (token_id);
