// cmd/mediamtx-pair is the CLI entry point for the Recorder join sequence.
//
// Usage (manual token):
//
//	raikada-pair [flags] <pairing-token>
//
// Usage (mDNS auto-discover, KAI-245):
//
//	raikada-pair --auto-discover [flags]
//
// Without --auto-discover the pairing-token positional argument is required.
// The pairing-token is the opaque string generated by the Directory admin
// (via POST /api/v1/pairing/tokens or the admin UI). Copy-paste it verbatim;
// it is base64url-encoded and never contains spaces.
//
// With --auto-discover the CLI listens on the LAN mDNS group for a
// "_mediamtx-directory._tcp.local." broadcast, presents the operator with
// the discovered Directory address, and (on confirmation) submits a pairing
// request to the Directory's approval queue. It then polls until the admin
// approves or the timeout elapses.
//
// On success the process exits 0 and the Recorder is ready to receive camera
// assignments from the Directory. On failure a clear error message identifies
// which step failed and what corrective action to take.
package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/bluenviron/mediamtx/internal/recorder/discovery"
	"github.com/bluenviron/mediamtx/internal/recorder/pairing"
)

func main() {
	fs := flag.NewFlagSet("raikada-pair", flag.ExitOnError)

	stateDir := fs.String("state-dir", "", "Recorder state directory (default /var/lib/mediamtx-recorder)")
	meshStateDir := fs.String("mesh-state-dir", "", "Mesh node state directory (default <state-dir>/mesh)")
	verbose := fs.Bool("v", false, "Enable verbose (debug) logging")
	autoDiscover := fs.Bool("auto-discover", false, "Discover the Directory via mDNS (KAI-245); no token argument required")
	discoverTimeout := fs.Duration("discover-timeout", discovery.DefaultDiscoverTimeout, "How long to listen for an mDNS broadcast (--auto-discover only)")
	approvalTimeout := fs.Duration("approval-timeout", discovery.DefaultApprovalTimeout, "How long to poll for admin approval after submitting a request (--auto-discover only)")
	yes := fs.Bool("yes", false, "Skip the 'Detected Directory at ... Join?' confirmation prompt (non-interactive use)")

	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: raikada-pair [flags] <pairing-token>\n")
		fmt.Fprintf(os.Stderr, "       raikada-pair --auto-discover [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
		fmt.Fprintf(os.Stderr, `
Manual mode:
  The pairing-token is printed by the Directory admin after generating a token
  via the admin UI or API. It is valid for 15 minutes and is single-use.

Auto-discover mode (--auto-discover):
  The CLI listens for a mDNS "_mediamtx-directory._tcp.local." broadcast for
  up to --discover-timeout, then submits a pairing request to the discovered
  Directory. An admin must approve the request within --approval-timeout.
  Use --yes to skip the interactive confirmation prompt.

Steps performed:
  1. Decode token, verify Directory TLS fingerprint (MITM protection)
  2. Probe hardware, POST check-in to Directory
  3. Register Recorder with tailnet mesh (Headscale)
  4. Generate encrypted device keypair
  5. Enroll with cluster CA (step-ca) to obtain mTLS leaf certificate
  6. Pin step-ca root certificate
  7. Verify Directory control-plane connectivity
  8. Request initial assignment snapshot
  9. Write paired state to local cache — Recorder ready

Security: The raw pairing token is never echoed to stdout or logs.
          Admin approval is always required in auto-discover mode.
`)
	}

	if err := fs.Parse(os.Args[1:]); err != nil {
		os.Exit(2)
	}

	// Set up logger.
	level := slog.LevelInfo
	if *verbose {
		level = slog.LevelDebug
	}
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: level}))
	slog.SetDefault(logger)

	// Interrupt handling.
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()

	joiner := pairing.NewJoiner(pairing.JoinerConfig{
		StateDir:     *stateDir,
		MeshStateDir: *meshStateDir,
		Logger:       logger,
	})

	if *autoDiscover {
		runAutoDiscover(ctx, joiner, logger, *discoverTimeout, *approvalTimeout, *yes)
		return
	}

	// Manual token mode.
	if fs.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "error: exactly one pairing-token argument required (or use --auto-discover)")
		fs.Usage()
		os.Exit(2)
	}
	rawToken := fs.Arg(0)

	if err := joiner.Run(ctx, rawToken); err != nil {
		printRunError(err)
		os.Exit(1)
	}

	fmt.Fprintln(os.Stdout, "Recorder paired successfully. Start the Recorder with: raikada recorder")
}

// runAutoDiscover implements the mDNS discovery + admin-approval flow.
func runAutoDiscover(
	ctx context.Context,
	joiner *pairing.Joiner,
	logger *slog.Logger,
	discoverTimeout, approvalTimeout time.Duration,
	skipPrompt bool,
) {
	ad := discovery.NewAutoDiscoverer(discovery.AutoDiscovererConfig{
		Logger: logger,
	})

	token, err := ad.Run(ctx, discovery.RunOptions{
		SkipPrompt:      skipPrompt,
		Stdin:           os.Stdin,
		Stdout:          os.Stdout,
		Stderr:          os.Stderr,
		DiscoverTimeout: discoverTimeout,
		ApprovalTimeout: approvalTimeout,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "auto-discover failed: %v\n", err)
		os.Exit(1)
	}

	// Run the normal 9-step join sequence with the received token.
	if err := joiner.Run(ctx, token); err != nil {
		printRunError(err)
		os.Exit(1)
	}

	fmt.Fprintln(os.Stdout, "Recorder paired successfully. Start the Recorder with: raikada recorder")
}

func printRunError(err error) {
	fmt.Fprintf(os.Stderr, "pairing failed: %v\n", err)
	fmt.Fprintf(os.Stderr, "\nTroubleshooting:\n")
	fmt.Fprintf(os.Stderr, "  - If step 1 fails: the token is malformed or expired. Request a new token.\n")
	fmt.Fprintf(os.Stderr, "  - If step 1 fails with 'fingerprint mismatch': possible MITM — verify the Directory URL.\n")
	fmt.Fprintf(os.Stderr, "  - If step 2 fails with 'already redeemed': a previous pairing attempt partially succeeded. Request a new token.\n")
	fmt.Fprintf(os.Stderr, "  - If step 2 fails with 'expired': the token expired in flight. Request a new token.\n")
	fmt.Fprintf(os.Stderr, "  - If step 3 fails: check network connectivity to the Directory and Headscale.\n")
	fmt.Fprintf(os.Stderr, "  - If step 5 fails: check that the Directory's StepCASignURL is configured.\n")
	fmt.Fprintf(os.Stderr, "  - If step 7 fails: the mTLS cert was not accepted by the Directory. Check step-ca provisioner config.\n")
}
