#!/usr/bin/env bash
# build-installer.sh — Builds a bootable Kaivue Recording Server installer image.
#
# This script produces a bootable ISO/USB image containing:
#   1. A minimal Debian 12 (Bookworm) base with cloud-init
#   2. The Kaivue server binary (mediamtx) pre-installed
#   3. A systemd service for the first-boot wizard
#   4. Hardware compatibility validation on first boot
#
# Usage:
#   ./scripts/build-installer.sh [--arch amd64|arm64] [--output <path>] [--version <tag>]
#
# Prerequisites:
#   - Go 1.22+ (for cross-compilation)
#   - xorriso or genisoimage (for ISO creation)
#   - debootstrap (for Debian chroot — optional, for full ISO builds)
#
# For CI, this script can also produce a "rootfs tarball" mode that skips
# ISO creation and just produces the file tree (useful for Docker/OCI images).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Defaults.
ARCH="amd64"
OUTPUT_DIR="$PROJECT_ROOT/dist/installer"
VERSION="${VERSION:-dev}"
MODE="tarball" # tarball or iso

usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Options:
  --arch     Target architecture: amd64 or arm64 (default: amd64)
  --output   Output directory (default: dist/installer)
  --version  Version tag (default: dev)
  --mode     Build mode: tarball or iso (default: tarball)
  -h|--help  Show this help
EOF
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --arch)    ARCH="$2"; shift 2 ;;
    --output)  OUTPUT_DIR="$2"; shift 2 ;;
    --version) VERSION="$2"; shift 2 ;;
    --mode)    MODE="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

echo "=== Kaivue Installer Build ==="
echo "  Arch:    $ARCH"
echo "  Version: $VERSION"
echo "  Mode:    $MODE"
echo "  Output:  $OUTPUT_DIR"
echo ""

# Step 1: Cross-compile the server binary.
echo "[1/4] Building mediamtx binary for linux/$ARCH..."
BINARY_PATH="$OUTPUT_DIR/rootfs/usr/local/bin/mediamtx"
mkdir -p "$(dirname "$BINARY_PATH")"
CGO_ENABLED=0 GOOS=linux GOARCH="$ARCH" go build \
  -ldflags "-s -w -X main.version=$VERSION" \
  -o "$BINARY_PATH" \
  "$PROJECT_ROOT"
echo "  -> $BINARY_PATH ($(stat -f%z "$BINARY_PATH" 2>/dev/null || stat -c%s "$BINARY_PATH") bytes)"

# Step 2: Build the hardware validation script.
echo "[2/4] Installing hardware validation script..."
HW_SCRIPT="$OUTPUT_DIR/rootfs/usr/local/bin/kaivue-hw-validate"
cp "$PROJECT_ROOT/scripts/hw-validate.sh" "$HW_SCRIPT"
chmod +x "$HW_SCRIPT"

# Step 3: Create systemd service and first-boot config.
echo "[3/4] Creating systemd units and first-boot config..."

SYSTEMD_DIR="$OUTPUT_DIR/rootfs/etc/systemd/system"
mkdir -p "$SYSTEMD_DIR"

cat > "$SYSTEMD_DIR/kaivue.service" <<'UNIT'
[Unit]
Description=Kaivue Recording Server
After=network-online.target
Wants=network-online.target
ConditionPathExists=/etc/kaivue/wizard-complete

[Service]
Type=simple
ExecStart=/usr/local/bin/mediamtx /etc/kaivue/mediamtx.yml
Restart=on-failure
RestartSec=5
LimitNOFILE=65536
WorkingDirectory=/var/lib/kaivue

# Security hardening.
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/var/lib/kaivue /var/lib/kaivue/recordings
ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
UNIT

cat > "$SYSTEMD_DIR/kaivue-firstboot.service" <<'UNIT'
[Unit]
Description=Kaivue First-Boot Setup Wizard
After=network-online.target
Wants=network-online.target
ConditionPathExists=!/etc/kaivue/wizard-complete
Before=kaivue.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=/usr/local/bin/kaivue-hw-validate
ExecStart=/usr/local/bin/mediamtx --first-boot-wizard
ExecStartPost=/bin/touch /etc/kaivue/wizard-complete
TimeoutStartSec=600

[Install]
WantedBy=multi-user.target
UNIT

# Step 3b: Default config directory.
KAIVUE_ETC="$OUTPUT_DIR/rootfs/etc/kaivue"
mkdir -p "$KAIVUE_ETC"

cat > "$KAIVUE_ETC/installer.conf" <<CONF
# Kaivue Installer Configuration
# Generated by build-installer.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
KAIVUE_VERSION=$VERSION
KAIVUE_ARCH=$ARCH
KAIVUE_FIRST_BOOT=true
CONF

# Step 3c: Data directories.
mkdir -p "$OUTPUT_DIR/rootfs/var/lib/kaivue/recordings"
mkdir -p "$OUTPUT_DIR/rootfs/var/lib/kaivue/state"

# Step 4: Package based on mode.
echo "[4/4] Packaging ($MODE)..."
case "$MODE" in
  tarball)
    TARBALL="$OUTPUT_DIR/kaivue-installer-${VERSION}-${ARCH}.tar.gz"
    tar -czf "$TARBALL" -C "$OUTPUT_DIR/rootfs" .
    echo "  -> $TARBALL"
    echo ""
    echo "=== Install on target system ==="
    echo "  sudo tar -xzf $(basename "$TARBALL") -C /"
    echo "  sudo systemctl daemon-reload"
    echo "  sudo systemctl enable kaivue-firstboot kaivue"
    echo "  sudo reboot  # triggers first-boot wizard"
    ;;
  iso)
    if ! command -v xorriso &>/dev/null && ! command -v genisoimage &>/dev/null; then
      echo "WARNING: xorriso/genisoimage not found — skipping ISO creation."
      echo "  Install with: apt-get install xorriso"
      echo "  Rootfs tarball is still available at: $OUTPUT_DIR/rootfs/"
      exit 0
    fi
    ISO_PATH="$OUTPUT_DIR/kaivue-installer-${VERSION}-${ARCH}.iso"
    if command -v xorriso &>/dev/null; then
      xorriso -as mkisofs \
        -o "$ISO_PATH" \
        -V "KAIVUE_INSTALLER" \
        -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
        -b isolinux/isolinux.bin \
        -c isolinux/boot.cat \
        -no-emul-boot \
        -boot-load-size 4 \
        -boot-info-table \
        "$OUTPUT_DIR/rootfs" 2>/dev/null || {
          echo "ISO creation failed (missing ISOLINUX — expected on CI). Rootfs is at: $OUTPUT_DIR/rootfs/"
        }
    fi
    if [[ -f "$ISO_PATH" ]]; then
      echo "  -> $ISO_PATH"
    fi
    ;;
  *)
    echo "Unknown mode: $MODE" >&2
    exit 1
    ;;
esac

echo ""
echo "=== Build complete ==="
