package pairing

import (
	"fmt"
	"net/http"
	"sync/atomic"
)

// Metrics tracks pairing-token lifecycle counters.
//
// These are emitted as Prometheus text exposition at /metrics (plugged in by
// the Directory HTTP router). Counter names are stable — do not rename them
// once the product ships.
type Metrics struct {
	Generated atomic.Uint64 // pairing_tokens_generated_total
	Redeemed  atomic.Uint64 // pairing_tokens_redeemed_total
	Expired   atomic.Uint64 // pairing_tokens_expired_total
}

// NewMetrics returns a zero-value Metrics.
func NewMetrics() *Metrics { return &Metrics{} }

// Handler returns an http.Handler that emits Prometheus text exposition.
// Mount it at /metrics (or merge with the server's existing /metrics mux).
func (m *Metrics) Handler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/plain; version=0.0.4")
		write := func(name, help string, val uint64) {
			fmt.Fprintf(w, "# HELP %s %s\n# TYPE %s counter\n%s %d\n",
				name, help, name, name, val)
		}
		write("pairing_tokens_generated_total",
			"Total number of pairing tokens generated by this Directory.",
			m.Generated.Load())
		write("pairing_tokens_redeemed_total",
			"Total number of pairing tokens successfully redeemed by a Recorder.",
			m.Redeemed.Load())
		write("pairing_tokens_expired_total",
			"Total number of pairing tokens swept as expired by the background job.",
			m.Expired.Load())
	})
}
