#!/bin/sh
set -e

case "$1" in
  remove|upgrade|deconfigure)
    # Stop and disable the service before removal
    systemctl stop mediamtx.service || true
    systemctl disable mediamtx.service || true
    ;;
esac

#DEBHELPER#

exit 0
